### PR TITLE
Added "your father"

### PR DESCRIPTION
**Pull request by NichlasHjorth**
added "your father" in <h1> in Mainpanel.js

### CODE REVIEW

**Review by TSKsmiley — APPROVED** [review]
lgtm

**Review by BaBrixx — CHANGES_REQUESTED** [review]
Forgot to add father?

**Review by TSKsmiley — APPROVED** [review]
lgtm for real this time

**Review by BaBrixx — APPROVED** [review]
LVGTM - Thank
index
s

**Pull request merged**
